### ISSUE TITLE
drop minimalistic-assert

### ISSUE THREAD

**Issue by fanatid** [indutny/des.js#1]
`console.assert` instead `minimalistic-assert` ?

**Comment by indutny** [comment]
@fanatid won't it pull in `assert`, `Buffer`, and all friends when browserified?

**Comment by fanatid** [comment]
It was checked yesterday :) https://github.com/dannycoates/int53/issues/1

**Comment by fanatid** [comment]
If you decide drop `minimalistic-assert`, please also drop in https://www.npmjs.com/package/asn1.js
in this case you drop `minimalistic-assert` for `crypto-browserify`

**Comment by fanatid** [comment]
ping @calvinmetcalf

**Comment by calvinmetcalf** [comment]
what browsers support console.assert?

**Comment by fanatid** [comment]
looks like all desktop browsers: https://developer.mozilla.org/en-US/docs/Web/API/console/assert
![screenshot at 2016-02-25 21 10 42](https://cloud.githubusercontent.com/assets/2633065/13329343/5e679fc8-dc04-11e5-8886-4003081845e8.png)
![screenshot at 2016-02-25 21 10 53](https://cloud.githubusercontent.com/assets/2633065/13329344/61390eda-dc04-11e5-95ed-ebcacbacd228.png)

**Comment by indutny** [comment]
Oh, at some point I thought that browserify polyfills it. But if it is not supported on mobile, I'd rather live with `minimalistic-assert` for now. Sorry!

**Comment by indutny** [comment]
Also, there is not much point in it. The package is so small that I don't see why we should care: https://github.com/calvinmetcalf/minimalistic-assert/blob/master/index.js

**Comment by fanatid** [comment]
It's ok, when I checked mdn page and seen that `console.assert` on mobile not supports (?) I thinking about closing this issue :)
